### ISSUE TITLE
Organizzazione wireframe

### ISSUE THREAD

**Issue by olistik** [scuoleparrocchialidesio/design#1]
Consiglio di creare una cartella `wireframe` dentro al quale inserire tutti i wireframe usando questa convenzione per i nomi dei file:

- `homepage--mobile.png` (l'uso di `--` per definire la specializzazione di un wireframe. Negli esempi di seguito uso il generico segnaposto `tipo`.)
- `homepage--desktop.png` (idem)
- `scuola-in-chiaro--tipo.png` (l'uso di `-` come separatore delle parole contenute nel nome di una sezione)
- `scuole--tipo.png`
- `scuola__calendario--tipo.png` (l'uso di `__` come separatore di sotto-sezioni)
- etc.

Avere tutti i wireframe nella stessa cartella, ordinati per sezione, permette di scorrerli velocemente.

**Comment by EnigmaEdivad** [comment]
Mi metto al lavoro
